apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: external-secrets-secret-accessor
spec:
  member: serviceAccount:external-secrets@gke-sandbox-412119.iam.gserviceaccount.com
  role: roles/secretmanager.secretAccessor
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1  
    kind: Project
    external: projects/gke-sandbox-412119
