apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: external-secrets-workload-identity
spec:
  member: "serviceAccount:gke-sandbox-412119.svc.id.goog[external-secrets/external-secrets]"
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: external-secrets
