apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: argocd
  annotations:
    cnrm.cloud.google.com/reconcile-interval-in-seconds: 15
spec:
  displayName: Argo CD service account
