apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecret
metadata:
  name: github-credentials-gabgrz
  labels:
    replication-type: automatic
spec:
  replication:
    automatic: true
