apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

bases:
- https://github.com/Gabgrz/argo-cd/manifests/cluster-install?ref=v2.9.1

resources:
- resources/namespace.yaml
- resources/projects.yaml
- resources/application-sets.yaml
- resources/github-authentication.yaml
- resources/gcp/argocd-service-account.yaml
- resources/gcp/github-credentials-gabgrz.yaml

patchesStrategicMerge:
- overlays/argocd-configmap.yaml
- overlays/server-service.yaml
